<?php

// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2011-03-09 14:40

$extensionClassesPath = t3lib_extMgm::extPath('me_shortlink ') . 'Classes/';
return array(
    'Tx_MeShortlink_Controller_ShortlinkController' => $extensionClassesPath . 'Controller/ShortlinkController.php',
    'Tx_MeShortlink_Domain_Model_Shortlink' => $extensionClassesPath . 'Domain/Model/Shortlink.php',
    'Tx_MeShortlink_Domain_Repository_ShortlinkRepository' => $extensionClassesPath . 'Domain/Repository/ShortlinkRepository.php',
);
?>