<?php

########################################################################
# Extension Manager/Repository config file for ext: "me_shortlink"
#
# Auto generated by Extension Builder 2012-10-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'm:e Shortlink Manager',
    'description' => 'Shortlink Manager',
    'category' => 'fe',
    'author' => 'Sascha Seyfert',
    'author_email' => 'sef@move-elevator.de',
    'author_company' => 'move:elevator',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.2.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.0.0-6.2.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
?>